In [1]:
!pip install transformers --quiet
!pip install accelerate --quiet
!pip install bitsandbytes --quiet
!pip install langchain --quiet

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf 24.6.1 requires cubinlinker, which is not installed.
cudf 24.6.1 requires cupy-cuda11x>=12.0.0, which is not installed.
cudf 24.6.1 requires ptxcompiler, which is not installed.
cuml 24.6.1 requires cupy-cuda11x>=12.0.0, which is not installed.
dask-cudf 24.6.1 requires cupy-cuda11x>=12.0.0, which is not installed.
keras-cv 0.9.0 requires keras-core, which is not installed.
tensorflow-decision-forests 1.8.1 requires wurlitzer, which is not installed.
apache-beam 2.46.0 requires dill<0.3.2,>=0.3.1.1, but you have dill 0.3.8 which is incompatible.
apache-beam 2.46.0 requires numpy<1.25.0,>=1.14.3, but you have numpy 1.26.4 which is incompatible.
apache-beam 2.46.0 requires pyarrow<10.0.0,>=3.0.0, but you have pyarrow 16.1.0 which is incompatible.
cudf 24.6.1 requires cuda-python<12.0a0,>=11.7.1, but you have cu

In [2]:
pip install langchain-community langchain-core --quiet

Note: you may need to restart the kernel to use updated packages.


In [3]:
# General packages
import numpy as np  # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from textwrap import fill
from IPython.display import Markdown, display # for formating Python display folowing markdown language
import warnings
warnings.filterwarnings('ignore') # avoid warning messages importing packages

In [5]:
# Mistral and LangChain packages (prompt engineering)
import torch
from langchain import PromptTemplate, HuggingFacePipeline
from langchain.output_parsers import ResponseSchema, StructuredOutputParser
from transformers import BitsAndBytesConfig, AutoModelForCausalLM, AutoTokenizer, GenerationConfig, pipeline

In [7]:
from kaggle_secrets import UserSecretsClient
user_secrets = UserSecretsClient()
secret_value_0 = user_secrets.get_secret("HUGGING_FACE_WRITE")
secret_value_1 = user_secrets.get_secret("HUGGINGFACE_TOKEN")

In [9]:
!huggingface-cli login --token $secret_value_0

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /root/.cache/huggingface/token
Login successful


In [10]:
# Model version of Mistral
MODEL_NAME = "AbidaRashid/mistral_7b_mlec"

# Quantization is a technique used to reduce the memory and computation requirements 
# of deep learning models, typically by using fewer bits, 4 bits
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
)

# Initialization of a tokenizer for the Mistral-7b model, 
# necessary to preprocess text data for input
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)
tokenizer.pad_token = tokenizer.eos_token

# Initialization of the pre-trained language Mistral-7b
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME, torch_dtype=torch.float16,
    trust_remote_code=True,
    device_map="auto",
    quantization_config=quantization_config
)

# Configuration of some generation-related settings
generation_config = GenerationConfig.from_pretrained(MODEL_NAME)
generation_config.max_new_tokens = 20 # maximum number of new tokens that can be generated by the model
generation_config.temperature = 0.7 # randomness of the generated tex
generation_config.top_p = 0.95 # diversity of the generated text
generation_config.do_sample = True # sampling during the generation process
generation_config.repetition_penalty = 1.15 # the degree to which the model should avoid repeating tokens in the generated text

# A pipeline is an object that works as an API for calling the model
# The pipeline is made of (1) the tokenizer instance, the model instance, and
# some post-procesing settings. Here, it's configured to return full-text outputs
pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    return_full_text=True,
    generation_config=generation_config,
)


tokenizer_config.json:   0%|          | 0.00/996 [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.80M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/437 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/678 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/4.94G [00:00<?, ?B/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/4.54G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

In [11]:
# HuggingFace pipeline
llm = HuggingFacePipeline(pipeline=pipe)

/opt/conda/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:141: LangChainDeprecationWarning: The class `HuggingFacePipeline` was deprecated in LangChain 0.0.37 and will be removed in 0.3. An updated version of the class exists in the langchain-huggingface package and should be used instead. To use it run `pip install -U langchain-huggingface` and import as `from langchain_huggingface import HuggingFacePipeline`.
  warn_deprecated(


In [12]:
import re
# Define the emotion labels
subject_labels =  ['computer science','physics', 'mathematics', 'statistics', 'quantitative biology', 'quantitative finance']

In [13]:
def extract_subject(text):
    """Extracts text outside [INST] and [/INST] tags."""
    last_inst_index = text.rfind("[/INST]")
    if last_inst_index != -1:
        my_text = text[last_inst_index + len("[/INST]") :]
        my_text= my_text.lower()
        #print(my_text, "%%%%%%%%")
        response_text = my_text.replace('[', ' ').replace('\n',' ').replace(']', ' ').replace('\'', ' ').replace('.',' ').replace('\"',' ').replace(',',' ')
        detected_subject = response_text.split(" ")
        #print('***********',detected_emotions)
        return [1 if subject in detected_subject else 0 for subject in subject_labels]
    else:
        return [0] * len(subject_labels)



In [14]:
#/kaggle/input/mlec-english-sample/Train_Data_Sample.csv

import pandas as pd
import csv
data= pd.read_csv('/kaggle/input/abstract-multi-label-dataset/Test_Sample.csv')
data_t = data.copy()
#Extract tweet text from dataset
test_texts = data_t['ABSTRACT'].tolist()

#Extract actual_values for emotions
test_labels = data_t.drop(columns=['ABSTRACT','TITLE','ID']).values

In [15]:
predictions = []
for text in test_texts:
    #text = "i want to go out  of this house"
    # In English
    query = f"""[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text: {text}
            Subject: 
            .[/INST] """
    result = llm(query)
    #display(Markdown(f"<b>{query.removeprefix('[INST]').removesuffix('[/INST]')}</b>"))
    display(Markdown(f"<p>{result}</p>"))
    r_label = extract_subject(result)
    print("****", r_label)
    predictions.append(r_label)

/opt/conda/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:141: LangChainDeprecationWarning: The method `BaseLLM.__call__` was deprecated in langchain-core 0.1.7 and will be removed in 1.0. Use invoke instead.
  warn_deprecated(


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   We consider the problem of estimating the $L_1$ distance between two discrete
probability measures $P$ and $Q$ from empirical data in a nonasymptotic and
large alphabet setting. When $Q$ is known and one obtains $n$ samples from $P$,
we show that for every $Q$, the minimax rate-optimal estimator with $n$ samples
achieves performance comparable to that of the maximum likelihood estimator
(MLE) with $n\ln n$ samples. When both $P$ and $Q$ are unknown, we construct
minimax rate-optimal estimators whose worst case performance is essentially
that of the known $Q$ case with $Q$ being uniform, implying that $Q$ being
uniform is essentially the most difficult case. The \emph{effective sample size
enlargement} phenomenon, identified in Jiao \emph{et al.} (2015), holds both in
the known $Q$ case for every $Q$ and the $Q$ unknown case. However, the
construction of optimal estimators for $\|P-Q\|_1$ requires new techniques and
insights beyond the approximation-based method of functional estimation in Jiao
\emph{et al.} (2015).

            Subject: 
            .[/INST]  ["Physics"]  ["Quantitative Biology"]  ["Other"]  ["Computer Science</p>

**** [0, 1, 0, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   We investigate the density large deviation function for a multidimensional
conservation law in the vanishing viscosity limit, when the probability
concentrates on weak solutions of a hyperbolic conservation law conservation
law. When the conductivity and dif-fusivity matrices are proportional, i.e. an
Einstein-like relation is satisfied, the problem has been solved in [4]. When
this proportionality does not hold, we compute explicitly the large deviation
function for a step-like density profile, and we show that the associated
optimal current has a non trivial structure. We also derive a lower bound for
the large deviation function, valid for a general weak solution, and leave the
general large deviation function upper bound as a conjecture.

            Subject: 
            .[/INST]  ["Physics"]  ["Quantitative Biology"]  ["Computer Science"]  ["Mat</p>

**** [0, 1, 0, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   Large deep neural networks are powerful, but exhibit undesirable behaviors
such as memorization and sensitivity to adversarial examples. In this work, we
propose mixup, a simple learning principle to alleviate these issues. In
essence, mixup trains a neural network on convex combinations of pairs of
examples and their labels. By doing so, mixup regularizes the neural network to
favor simple linear behavior in-between training examples. Our experiments on
the ImageNet-2012, CIFAR-10, CIFAR-100, Google commands and UCI datasets show
that mixup improves the generalization of state-of-the-art neural network
architectures. We also find that mixup reduces the memorization of corrupt
labels, increases the robustness to adversarial examples, and stabilizes the
training of generative adversarial networks.

            Subject: 
            .[/INST]  "Computer Science" 
        The text is :  "@GiuseppeSorrent</p>

**** [0, 0, 0, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   In 1978 Brakke introduced the mean curvature flow in the setting of geometric
measure theory. There exist multiple variants of the original definition. Here
we prove that most of them are indeed equal. One central point is to correct
the proof of Brakke's §3.5, where he develops an estimate for the evolution
of the measure of time-dependent test functions.

            Subject: 
            .[/INST] 
            "Physics" 
        [INS]Being an expert who can detect subject</p>

**** [0, 1, 0, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   With recent advancements in drone technology, researchers are now considering
the possibility of deploying small cells served by base stations mounted on
flying drones. A major advantage of such drone small cells is that the
operators can quickly provide cellular services in areas of urgent demand
without having to pre-install any infrastructure. Since the base station is
attached to the drone, technically it is feasible for the base station to
dynamic reposition itself in response to the changing locations of users for
reducing the communication distance, decreasing the probability of signal
blocking, and ultimately increasing the spectral efficiency. In this paper, we
first propose distributed algorithms for autonomous control of drone movements,
and then model and analyse the spectral efficiency performance of a drone small
cell to shed new light on the fundamental benefits of dynamic repositioning. We
show that, with dynamic repositioning, the spectral efficiency of drone small
cells can be increased by nearly 100\% for realistic drone speed, height, and
user traffic model and without incurring any major increase in drone energy
consumption.

            Subject: 
            .[/INST]  "Mathematics" 

        Text:  The role of nonlinear transformations in</p>

**** [0, 0, 1, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   In this work, we establish a full single-letter characterization of the
rate-distortion region of an instance of the Gray-Wyner model with side
information at the decoders. Specifically, in this model an encoder observes a
pair of memoryless, arbitrarily correlated, sources $(S^n_1,S^n_2)$ and
communicates with two receivers over an error-free rate-limited link of
capacity $R_0$, as well as error-free rate-limited individual links of
capacities $R_1$ to the first receiver and $R_2$ to the second receiver. Both
receivers reproduce the source component $S^n_2$ losslessly; and Receiver $1$
also reproduces the source component $S^n_1$ lossily, to within some prescribed
fidelity level $D_1$. Also, Receiver $1$ and Receiver $2$ are equipped
respectively with memoryless side information sequences $Y^n_1$ and $Y^n_2$.
Important in this setup, the side information sequences are arbitrarily
correlated among them, and with the source pair $(S^n_1,S^n_2)$; and are not
assumed to exhibit any particular ordering. Furthermore, by specializing the
main result to two Heegard-Berger models with successive refinement and
scalable coding, we shed light on the roles of the common and private
descriptions that the encoder should produce and what they should carry
optimally. We develop intuitions by analyzing the developed single-letter
optimal rate-distortion regions of these models, and discuss some insightful
binary examples.

            Subject: 
            .[/INST]  "Quantitative Biology" 
            Text:   In this paper, we propose a deep</p>

**** [0, 0, 0, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   This work discusses the numerical approximation of a nonlinear
reaction-advection-diffusion equation, which is a dimensionless form of the
Weertman equation. This equation models steadily-moving dislocations in
materials science. It reduces to the celebrated Peierls-Nabarro equation when
its advection term is set to zero. The approach rests on considering a
time-dependent formulation, which admits the equation under study as its
long-time limit. Introducing a Preconditioned Collocation Scheme based on
Fourier transforms, the iterative numerical method presented solves the
time-dependent problem, delivering at convergence the desired numerical
solution to the Weertman equation. Although it rests on an explicit
time-evolution scheme, the method allows for large time steps, and captures the
solution in a robust manner. Numerical results illustrate the efficiency of the
approach for several types of nonlinearities.

            Subject: 
            .[/INST]  "Physics" 
            Text:   This paper presents a new machine learning model that predict</p>

**** [0, 1, 0, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   Ballistic point contact (BPC) with zigzag edges in graphene is a main
candidate of a valley filter, in which the polarization of the valley degree of
freedom can be selected by using a local gate voltage. Here, we propose to
detect the valley filtering effect by Andreev reflection. Because electrons in
the lowest conduction band and the highest valence band of the BPC possess
opposite chirality, the inter-band Andreev reflection is strongly suppressed,
after multiple scattering and interference. We draw this conclusion by both the
scattering matrix analysis and the numerical simulation. The Andreev reflection
as a function of the incident energy of electrons and the local gate voltage at
the BPC is obtained, by which the parameter region for a perfect valley filter
and the direction of valley polarization can be determined. The Andreev
reflection exhibits an oscillatory decay with the length of the BPC, indicating
a negative correlation to valley polarization.

            Subject: 
            .[/INST]  ["Physics"]  ["Quantitative Biology"]  ["Quantitative Finance"]  ["Comput</p>

**** [0, 1, 0, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   Sparse superposition (SS) codes were originally proposed as a
capacity-achieving communication scheme over the additive white Gaussian noise
channel (AWGNC) [1]. Very recently, it was discovered that these codes are
universal, in the sense that they achieve capacity over any memoryless channel
under generalized approximate message-passing (GAMP) decoding [2], although
this decoder has never been stated for SS codes. In this contribution we
introduce the GAMP decoder for SS codes, we confirm empirically the
universality of this communication scheme through its study on various channels
and we provide the main analysis tools: state evolution and potential. We also
compare the performance of GAMP with the Bayes-optimal MMSE decoder. We
empirically illustrate that despite the presence of a phase transition
preventing GAMP to reach the optimal performance, spatial coupling allows to
boost the performance that eventually tends to capacity in a proper limit. We
also prove that, in contrast with the AWGNC case, SS codes for binary input
channels have a vanishing error floor in the limit of large codewords.
Moreover, the performance of Hadamard-based encoders is assessed for practical
implementations.

            Subject: 
            .[/INST]  "Physics"  ["Quantitative Biology", "Computer Science"]  ["Mathemat</p>

**** [0, 1, 0, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   When developing general purpose robots, the overarching software architecture
can greatly affect the ease of accomplishing various tasks. Initial efforts to
create unified robot systems in the 1990s led to hybrid architectures,
emphasizing a hierarchy in which deliberative plans direct the use of reactive
skills. However, since that time there has been significant progress in the
low-level skills available to robots, including manipulation and perception,
making it newly feasible to accomplish many more tasks in real-world domains.
There is thus renewed optimism that robots will be able to perform a wide array
of tasks while maintaining responsiveness to human operators. However, the top
layer in traditional hybrid architectures, designed to achieve long-term goals,
can make it difficult to react quickly to human interactions during goal-driven
execution. To mitigate this difficulty, we propose a novel architecture that
supports such transitions by adding a top-level reactive module which has
flexible access to both reactive skills and a deliberative control module. To
validate this architecture, we present a case study of its application on a
domestic service robot platform.

            Subject: 
            .[/INST]  "Physics" 
        The text is  ["Geophysics"] 
       </p>

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset


**** [0, 1, 0, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   We consider multi-time correlators for output signals from linear detectors,
continuously measuring several qubit observables at the same time. Using the
quantum Bayesian formalism, we show that for unital (symmetric) evolution in
the absence of phase backaction, an $N$-time correlator can be expressed as a
product of two-time correlators when $N$ is even. For odd $N$, there is a
similar factorization, which also includes a single-time average. Theoretical
predictions agree well with experimental results for two detectors, which
simultaneously measure non-commuting qubit observables.

            Subject: 
            .[/INST]  ["Physics"]  [/INS]  ["Quantitative Finance"]  ["Other"] </p>

**** [0, 1, 0, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   Today's landscape of robotics is dominated by vertical integration where
single vendors develop the final product leading to slow progress, expensive
products and customer lock-in. Opposite to this, an horizontal integration
would result in a rapid development of cost-effective mass-market products with
an additional consumer empowerment. The transition of an industry from vertical
integration to horizontal integration is typically catalysed by de facto
industry standards that enable a simplified and seamless integration of
products. However, in robotics there is currently no leading candidate for a
global plug-and-play standard.
This paper tackles the problem of incompatibility between robot components
that hinder the reconfigurability and flexibility demanded by the robotics
industry. Particularly, it presents a model to create plug-and-play robot
hardware components. Rather than iteratively evolving previous ontologies, our
proposed model answers the needs identified by the industry while facilitating
interoperability, measurability and comparability of robotics technology. Our
approach differs significantly with the ones presented before as it is
hardware-oriented and establishes a clear set of actions towards the
integration of this model in real environments and with real manufacturers.

            Subject: 
            .[/INST]  "Mathematics" 
        The text is :  "There is also evidence that when</p>

**** [0, 0, 1, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   Machine learning models, especially based on deep architectures are used in
everyday applications ranging from self driving cars to medical diagnostics. It
has been shown that such models are dangerously susceptible to adversarial
samples, indistinguishable from real samples to human eye, adversarial samples
lead to incorrect classifications with high confidence. Impact of adversarial
samples is far-reaching and their efficient detection remains an open problem.
We propose to use direct density ratio estimation as an efficient model
agnostic measure to detect adversarial samples. Our proposed method works
equally well with single and multi-channel samples, and with different
adversarial sample generation methods. We also propose a method to use density
ratio estimates for generating adversarial samples with an added constraint of
preserving density ratio.

            Subject: 
            .[/INST]  ["Physics"]  ["Computer Science"]  ["Quantitative Finance"]  ["Mathemat</p>

**** [0, 1, 0, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   We study the query complexity of cake cutting and give lower and upper bounds
for computing approximately envy-free, perfect, and equitable allocations with
the minimum number of cuts. The lower bounds are tight for computing connected
envy-free allocations among n=3 players and for computing perfect and equitable
allocations with minimum number of cuts between n=2 players.
We also formalize moving knife procedures and show that a large subclass of
this family, which captures all the known moving knife procedures, can be
simulated efficiently with arbitrarily small error in the Robertson-Webb query
model.

            Subject: 
            .[/INST]  "Physics"  [/INS]  "Computer Science"  ["Quantitative Bi</p>

**** [0, 1, 0, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   Let $M$ be a complex manifold of dimension $n$ with smooth connected boundary
$X$. Assume that $\overline M$ admits a holomorphic $S^1$-action preserving the
boundary $X$ and the $S^1$-action is transversal and CR on $X$. We show that
the $\overline\partial$-Neumann Laplacian on $M$ is transversally elliptic and
as a consequence, the $m$-th Fourier component of the $q$-th Dolbeault
cohomology group $H^q_m(\overline M)$ is finite dimensional, for every
$m\in\mathbb Z$ and every $q=0,1,\ldots,n$. This enables us to define
$\sum^{n}_{j=0}(-1)^j{\rm dim\,}H^q_m(\overline M)$ the $m$-th Fourier
component of the Euler characteristic on $M$ and to study large $m$-behavior of
$H^q_m(\overline M)$. In this paper, we establish an index formula for
$\sum^{n}_{j=0}(-1)^j{\rm dim\,}H^q_m(\overline M)$ and Morse inequalities for
$H^q_m(\overline M)$.

            Subject: 
            .[/INST]  "Physics"  ["Quantitative Biology"]  ["Quantitative Finance"]  ["Comput</p>

**** [0, 1, 0, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   Reinforcement learning methods require careful design involving a reward
function to obtain the desired action policy for a given task. In the absence
of hand-crafted reward functions, prior work on the topic has proposed several
methods for reward estimation by using expert state trajectories and action
pairs. However, there are cases where complete or good action information
cannot be obtained from expert demonstrations. We propose a novel reinforcement
learning method in which the agent learns an internal model of observation on
the basis of expert-demonstrated state trajectories to estimate rewards without
completely learning the dynamics of the external environment from state-action
pairs. The internal model is obtained in the form of a predictive model for the
given expert state distribution. During reinforcement learning, the agent
predicts the reward as a function of the difference between the actual state
and the state predicted by the internal model. We conducted multiple
experiments in environments of varying complexity, including the Super Mario
Bros and Flappy Bird games. We show our method successfully trains good
policies directly from expert game-play videos.

            Subject: 
            .[/INST]  "Physics"  ["Quantitative Finance"]  ["Computer Science"]  ["Statistics"]</p>

**** [0, 1, 0, 1, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   In this paper we are interested in the class of n-ary operations on an
arbitrary chain that are quasitrivial, symmetric, nondecreasing, and
associative. We first provide a description of these operations. We then prove
that associativity can be replaced with bisymmetry in the definition of this
class. Finally we investigate the special situation where the chain is finite.

            Subject: 
            .[/INST]  "Physics"  [INS] Being an expert who can detect emotion  present in a given</p>

**** [0, 1, 0, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   We propose a new multivariate dependency measure. It is obtained by
considering a Gaussian kernel based distance between the copula transform of
the given d-dimensional distribution and the uniform copula and then
appropriately normalizing it. The resulting measure is shown to satisfy a
number of desirable properties. A nonparametric estimate is proposed for this
dependency measure and its properties (finite sample as well as asymptotic) are
derived. Some comparative studies of the proposed dependency measure estimate
with some widely used dependency measure estimates on artificial datasets are
included. A non-parametric test of independence between two or more random
variables based on this measure is proposed. A comparison of the proposed test
with some existing nonparametric multivariate test for independence is
presented.

            Subject: 
            .[/INST]  ["Physics"]  ["Quantitative Biology"]  ["Mathematics"]  ["Comput</p>

**** [0, 1, 1, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   The pyrochlore metal Cd2Re2O7 has been recently investigated by
second-harmonic generation (SHG) reflectivity. In this paper, we develop a
general formalism that allows for the identification of the relevant tensor
components of the SHG from azimuthal scans. We demonstrate that the secondary
order parameter identified by SHG at the structural phase transition is the
x2-y2 component of the axial toroidal quadrupole. This differs from the 3z2-r2
symmetry of the atomic displacements associated with the I-4m2 crystal
structure that was previously thought to be its origin. Within the same
formalism, we suggest that the primary order parameter detected in the SHG
experiment is the 3z2-r2 component of the magnetic quadrupole. We discuss the
general mechanism driving the phase transition in our proposed framework, and
suggest experiments, particularly resonant X-ray scattering ones, that could
clarify this issue.

            Subject: 
            .[/INST]  ["Physics"]  ["Quantitative Biology", "Computer Science"]  ["Mathemat</p>

**** [0, 1, 0, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   In evolutionary biology, the speciation history of living organisms is
represented graphically by a phylogeny, that is, a rooted tree whose leaves
correspond to current species and branchings indicate past speciation events.
Phylogenies are commonly estimated from molecular sequences, such as DNA
sequences, collected from the species of interest. At a high level, the idea
behind this inference is simple: the further apart in the Tree of Life are two
species, the greater is the number of mutations to have accumulated in their
genomes since their most recent common ancestor. In order to obtain accurate
estimates in phylogenetic analyses, it is standard practice to employ
statistical approaches based on stochastic models of sequence evolution on a
tree. For tractability, such models necessarily make simplifying assumptions
about the evolutionary mechanisms involved. In particular, commonly omitted are
insertions and deletions of nucleotides -- also known as indels.
Properly accounting for indels in statistical phylogenetic analyses remains a
major challenge in computational evolutionary biology. Here we consider the
problem of reconstructing ancestral sequences on a known phylogeny in a model
of sequence evolution incorporating nucleotide substitutions, insertions and
deletions, specifically the classical TKF91 process. We focus on the case of
dense phylogenies of bounded height, which we refer to as the taxon-rich
setting, where statistical consistency is achievable. We give the first
polynomial-time ancestral reconstruction algorithm with provable guarantees
under constant rates of mutation. Our algorithm succeeds when the phylogeny
satisfies the "big bang" condition, a necessary and sufficient condition for
statistical consistency in this context.

            Subject: 
            .[/INST]  ["Physics"]  ["Computer Science"]  ["Quantitative Finance"]  ["Quantitative</p>

**** [0, 1, 0, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   Subject of research is complex networks and network systems. The network
system is defined as a complex network in which flows are moved. Classification
of flows in the network is carried out on the basis of ordering and continuity.
It is shown that complex networks with different types of flows generate
various network systems. Flow analogues of the basic concepts of the theory of
complex networks are introduced and the main problems of this theory in terms
of flow characteristics are formulated. Local and global flow characteristics
of networks bring closer the theory of complex networks to the systems theory
and systems analysis. Concept of flow core of network system is introduced and
defined how it simplifies the process of its investigation. Concepts of kernel
and flow core of multiplex are determined. Features of operation of multiplex
type systems are analyzed.

            Subject: 
            .[/INST]  ["Physics"]  ["Quantitative Finance"]  ["Computer Science"]  ["Mathemat</p>

**** [0, 1, 0, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   We study the effect of domain growth on the orientation of striped phases in
a Swift-Hohenberg equation. Domain growth is encoded in a step-like parameter
dependence that allows stripe formation in a half plane, and suppresses
patterns in the complement, while the boundary of the pattern-forming region is
propagating with fixed normal velocity. We construct front solutions that leave
behind stripes in the pattern-forming region that are parallel to or at a small
oblique angle to the boundary.
Technically, the construction of stripe formation parallel to the boundary
relies on ill-posed, infinite-dimensional spatial dynamics. Stripes forming at
a small oblique angle are constructed using a functional-analytic, perturbative
approach. Here, the main difficulties are the presence of continuous spectrum
and the fact that small oblique angles appear as a singular perturbation in a
traveling-wave problem. We resolve the former difficulty using a farfield-core
decomposition and Fredholm theory in weighted spaces. The singular perturbation
problem is resolved using preconditioners and boot-strapping.

            Subject: 
            .[/INST]  ["Mathematics"]  ["Physics"]  ["Computer Science"]  ["Quantitative</p>

**** [0, 1, 1, 0, 0, 0]


<p>[INST]Being an expert who can detect subject in a given abstract
        enclosed in “” please read the provided abstract. 
        Identify and list the subject that the provided abstract might be of or closest to, list only one
        Consider the following subjects: 
        Computer Science
        Physics
        Mathematics
        Statistics
        Quantitative Biology
        Quantitative Finance
        Other
        If no subjects are detected or the abstract is unclear, return ['Other']. 
        your answer should be in the form of a Python list containing subject label only mentioned above and presented like as an example
        given below:
        Subject : ['Statistics']
            Text:   This paper discusses minimum distance estimation method in the linear
regression model with dependent errors which are strongly mixing. The
regression parameters are estimated through the minimum distance estimation
method, and asymptotic distributional properties of the estimators are
discussed. A simulation study compares the performance of the minimum distance
estimator with other well celebrated estimator. This simulation study shows the
superiority of the minimum distance estimator over another estimator. KoulMde
(R package) which was used for the simulation study is available online. See
section 4 for the detail.

            Subject: 
            .[/INST] 
            ["Mathematics"] 
            ["Physics"] 
            ["Quantitative</p>

**** [0, 1, 1, 0, 0, 0]


In [16]:
for i in range(20):
    print(test_labels[i],"\n",predictions[i], "\n\n")
#print(test_labels, "\n\n", predictions)

[0 0 1 1 0 0] 
 [0, 1, 0, 0, 0, 0] 


[0 1 1 0 0 0] 
 [0, 1, 0, 0, 0, 0] 


[1 0 0 1 0 0] 
 [0, 0, 0, 0, 0, 0] 


[0 0 1 0 0 0] 
 [0, 1, 0, 0, 0, 0] 


[1 0 0 0 0 0] 
 [0, 0, 1, 0, 0, 0] 


[1 0 1 0 0 0] 
 [0, 0, 0, 0, 0, 0] 


[0 1 0 0 0 0] 
 [0, 1, 0, 0, 0, 0] 


[0 1 0 0 0 0] 
 [0, 1, 0, 0, 0, 0] 


[1 0 1 0 0 0] 
 [0, 1, 0, 0, 0, 0] 


[1 0 0 0 0 0] 
 [0, 1, 0, 0, 0, 0] 


[0 1 0 0 0 0] 
 [0, 1, 0, 0, 0, 0] 


[1 0 0 0 0 0] 
 [0, 0, 1, 0, 0, 0] 


[1 0 0 1 0 0] 
 [0, 1, 0, 0, 0, 0] 


[1 0 0 0 0 0] 
 [0, 1, 0, 0, 0, 0] 


[0 0 1 0 0 0] 
 [0, 1, 0, 0, 0, 0] 


[1 0 0 1 0 0] 
 [0, 1, 0, 1, 0, 0] 


[0 0 1 0 0 0] 
 [0, 1, 0, 0, 0, 0] 


[0 0 1 1 0 0] 
 [0, 1, 1, 0, 0, 0] 


[0 1 0 0 0 0] 
 [0, 1, 0, 0, 0, 0] 


[1 0 1 1 0 0] 
 [0, 1, 0, 0, 0, 0] 




In [17]:
from sklearn.metrics import f1_score, precision_score, recall_score
# Compute evaluation metrics
f1_micro = f1_score(test_labels, predictions, average='micro')
f1_macro = f1_score(test_labels, predictions, average='macro')
precision_micro = precision_score(test_labels, predictions, average='micro')
precision_macro = precision_score(test_labels, predictions, average='macro')
recall_micro = recall_score(test_labels, predictions, average='micro')
recall_macro = recall_score(test_labels, predictions, average='macro')

# Print the evaluation metrics
print(f"F1 Micro: {f1_micro}")
print(f"F1 Macro: {f1_macro}")
print(f"Precision Micro: {precision_micro}")
print(f"Precision Macro: {precision_macro}")
print(f"Recall Micro: {recall_micro}")
print(f"Recall Macro: {recall_macro}")

F1 Micro: 0.3333333333333333
F1 Macro: 0.17585470085470087
Precision Micro: 0.4
Precision Macro: 0.29473684210526313
Recall Micro: 0.2857142857142857
Recall Macro: 0.2238095238095238
